name: setup-nix

inputs:
  system:
    required: true
  large:
    default: 'false'
  attic-token:
    required: true

runs:
  using: composite
  steps:
    - name: "Create Directory for Nix Store"
      if: ${{ inputs.large != 'true' }}
      shell: bash
      run: |
        sudo mkdir /nix
    - name: "Maximize Disk Space"
      if: ${{ inputs.large == 'true' }}
      uses: wimpysworld/nothing-but-nix@687c797a730352432950c707ab493fcc951818d7 # v10

    # We only run this if we are building an aarch64-linux system
    - if: inputs.system == 'aarch64-linux'
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

    - uses: cachix/install-nix-action@96951a368ba55167b55f1c916f7d416bac6505fe # v31.10.3
      with:
        extra_nix_config: |
          fallback = true
          http-connections = 128
          max-substitution-jobs = 128
          extra-platforms = i686-linux aarch64-linux
          substituters = https://nix-cache.diogotc.com/dtc?priority=43 https://cache.nixos.org/
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= dtc:HU5hQrzlNDSFAcA/kvzKx+IhyDYLvR+xUS/1drh3o2U=
          allow-import-from-derivation = false
          abort-on-warn = true

    # We make our netrc file that is used to make authorized requests to Attic
    - name: setup netrc
      shell: bash
      run: |
        echo "machine nix-cache.diogotc.com password ${{ inputs.attic-token }}" | sudo tee /etc/nix/netrc > /dev/null
