{
  chromium,
  fetchFromGitHub,
  fetchYarnDeps,
  makeWrapper,
  node-gyp,
  nodejs,
  pkg-config,
  python3,
  stdenv,
  vips,
  yarnConfigHook,
  yarnInstallHook,
  ...
}:
let
  pin = {
    version = "3.1.1";
    srcHash = "sha256-cbMH8u7vVNsbQFmOtzTbll6ZfF3eqJtxiaLV9A2BFhA=";
    yarnSha256 = "sha256-jlwg/QLIMuA45C36oQQ6BA7Yhp3y8LGktZyFH0d1F40=";
  };
in
stdenv.mkDerivation (finalAttrs: {
  pname = "book-metadata-api";
  inherit (pin) version;

  src = fetchFromGitHub {
    owner = "livraria-papelaria-espaco";
    repo = "book-metadata-api";
    rev = "v${finalAttrs.version}";
    hash = pin.srcHash;
  };

  yarnOfflineCache = fetchYarnDeps {
    yarnLock = finalAttrs.src + "/yarn.lock";
    sha256 = pin.yarnSha256;
  };

  buildInputs = [
    vips
  ];

  nativeBuildInputs = [
    yarnConfigHook
    yarnInstallHook
    nodejs
    makeWrapper
    chromium
    pkg-config
    node-gyp
    python3
  ];

  env.SHARP_FORCE_GLOBAL_LIBVIPS = 1;

  # generate sharp .node binary
  preBuild = ''
    export npm_config_nodedir=${nodejs}
    (
      cd node_modules/sharp
      yarn --offline run install
    )
  '';

  # the node_modules directory will be regenerated by yarnInstallHook, so we save our .node binaries
  preInstall = ''
    cp node_modules/sharp/build/Release/sharp*.node .
  '';

  postInstall = ''
    # restore .node binaries
    install -Dm755 sharp*.node -t $out/lib/node_modules/book-metadata-api/node_modules/sharp/build/Release

    # Remove unneeded files
    rm $out/lib/node_modules/book-metadata-api/{.dockerignore,docker-compose.yml,flake.*,README.md}

    makeWrapper '${nodejs}/bin/node' "$out/bin/book-metadata-api" \
      --add-flags "$out/lib/node_modules/book-metadata-api/src/index.js" \
      --set PUPPETEER_SKIP_DOWNLOAD 1 \
      --set PUPPETEER_EXECUTABLE_PATH ${chromium}/bin/chromium
  '';

  meta = {
    mainProgram = "book-metadata-api";
  };
})
